from pipeline.models.asset_manifest import RightsStatus
from pipeline.models.compliance import ComplianceFinding, ComplianceReport, ComplianceSeverity
from pipeline.models.production_artifact import ProductionArtifact
from pipeline.models.review import ReviewStatus
from pipeline.models.cue_ledger import AssetType


BLOCKED_INCOME_PHRASES = [
    "guaranteed profit",
    "risk-free income",
    "free money",
    "get rich quick",
]

FINANCIAL_KEYWORDS = [
    "invest",
    "stock",
    "crypto",
    "bitcoin",
    "trading",
    "finance",
    "revenue",
    "wealth",
]


def check_compliance(artifact: ProductionArtifact) -> ComplianceReport:
    findings: list[ComplianceFinding] = []
    script = (artifact.approved_script_markdown or "").lower()

    # 1. Misleading Income Claims Check (Financial Gate)
    for phrase in BLOCKED_INCOME_PHRASES:
        if phrase in script:
            findings.append(
                ComplianceFinding(
                    code="misleading_income_claim",
                    severity=ComplianceSeverity.BLOCKER,
                    message=f"Script contains blocked misleading phrase: '{phrase}'",
                )
            )

    # 2. Financial Disclaimer Check (Financial Gate)
    is_financial_topic = any(kw in script for kw in FINANCIAL_KEYWORDS) or (artifact.genre == "finance")
    has_disclaimer = "disclosure" in script or "disclaimer" in script or "risk" in script or "invest at your own risk" in script
    if is_financial_topic and not has_disclaimer:
        findings.append(
            ComplianceFinding(
                code="financial_disclaimer_missing",
                severity=ComplianceSeverity.BLOCKER,
                message="Financial topic detected but script is missing a risk disclosure or disclaimer.",
            )
        )

    # 3. AI Disclosure Check (AI Gate)
    has_ai_assets = False
    if artifact.asset_manifest:
        for asset in artifact.asset_manifest.assets:
            if asset.asset_type == AssetType.GENERATED_IMAGE:
                has_ai_assets = True
                break
    # Check if voiceover is using TTS
    if artifact.voiceover_path and "silent" not in str(artifact.voiceover_path).lower():
        has_ai_assets = True

    if has_ai_assets:
        # Check if user has included AI disclosure in title/description
        pkg_desc = ""
        if artifact.video_packaging and "description" in artifact.video_packaging:
            pkg_desc = str(artifact.video_packaging.get("description", "")).lower()
        
        import re
        has_ai_word = bool(re.search(r"\bai\b", pkg_desc, re.IGNORECASE))
        has_ai_mention = "ai-generated" in script or "synthetic" in script or has_ai_word or "generated by ai" in pkg_desc
        if not has_ai_mention:
            findings.append(
                ComplianceFinding(
                    code="ai_disclosure_needed",
                    severity=ComplianceSeverity.WARNING,
                    message="AI-generated voice or images used, but no AI disclosure was found in the script/metadata description.",
                )
            )

    # 4. Originality & Length Check (Originality Gate)
    word_count = len(script.split())
    if word_count > 0 and word_count < 30:
        findings.append(
            ComplianceFinding(
                code="low_originality_risk",
                severity=ComplianceSeverity.WARNING,
                message=f"Script is very short ({word_count} words). High risk of repetitive or low-originality content.",
            )
        )

    # 5. Asset Commercial Rights Check (Asset Rights Gate)
    if artifact.asset_manifest:
        for asset in artifact.asset_manifest.assets:
            if asset.rights_status != RightsStatus.APPROVED:
                findings.append(
                    ComplianceFinding(
                        code="asset_rights_needs_review",
                        severity=ComplianceSeverity.BLOCKER,
                        message="Asset requires human commercial-rights review.",
                        cue_id=asset.cue_id,
                        evidence_ref=asset.asset_id,
                    )
                )

    # 6. Final Review Approval Gate (Review Gate)
    if artifact.review_status != ReviewStatus.APPROVED:
        findings.append(
            ComplianceFinding(
                code="final_preview_not_approved",
                severity=ComplianceSeverity.BLOCKER,
                message="Final preview must be approved before upload.",
            )
        )

    # 7. Visual Quality Blocker Gate (Quality Gate)
    if artifact.visual_qc_report:
        for visual_finding in artifact.visual_qc_report.findings:
            if visual_finding.severity == "blocker":
                findings.append(
                    ComplianceFinding(
                        code=f"visual_{visual_finding.code}",
                        severity=ComplianceSeverity.BLOCKER,
                        message=visual_finding.message,
                        cue_id=visual_finding.cue_id,
                    )
                )

    upload_ready = artifact.review_status == ReviewStatus.APPROVED and not any(
        f.severity == ComplianceSeverity.BLOCKER for f in findings
    )
    return ComplianceReport(project_id=artifact.project_id, upload_ready=upload_ready, findings=findings)
